import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Cookie Policy | Hair Restoration of Lehigh Valley',
  robots: 'noindex, nofollow',
}

const DARK  = '#043939'
const WHITE = '#ffffff'

export default function CookiePolicyPage() {
  return (
    <div style={{ fontFamily: "'Jost', 'Open Sans', sans-serif", color: '#1a1a1a', background: WHITE }}>

      {/* Header */}
      <header style={{ background: WHITE, padding: '20px 48px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', boxShadow: '0 2px 8px rgba(0,0,0,0.08)' }}>
        <img src="/logo-pa.webp" alt="Hair Restoration of Lehigh Valley" style={{ height: 56, width: 'auto' }} />
        <a href="tel:4842762638" style={{ color: DARK, textDecoration: 'none', fontSize: 16, fontWeight: 600 }}>
          484-276-2638
        </a>
      </header>

      {/* Banner */}
      <div style={{ background: DARK, padding: '48px 48px', textAlign: 'center' }}>
        <h1 style={{ fontFamily: "'Cormorant Infant', Georgia, serif", fontWeight: 700, color: WHITE, fontSize: 40, textTransform: 'uppercase', margin: 0, lineHeight: 1.129 }}>Cookie Policy</h1>
        <p style={{ color: 'rgba(255,255,255,0.7)', margin: '12px 0 0', fontSize: 14 }}>Last Updated: September 12, 2025</p>
      </div>

      {/* Content */}
      <main style={{ maxWidth: 860, margin: '0 auto', padding: '64px 48px' }}>

        <Section title="What Are Cookies">
          <p>As is common practice with almost all professional websites, this site uses cookies, which are tiny files that are downloaded to your computer to improve your experience. This page describes what information they gather, how we use it, and why we sometimes need to store these cookies. We will also share how you can prevent these cookies from being stored, however this may downgrade or break certain elements of the site&apos;s functionality.</p>
          <p>For more general information on cookies see the Wikipedia article on HTTP Cookies.</p>
        </Section>

        <Section title="First and Third Party Cookies">
          <p>Whether a cookie is &apos;first party&apos; or &apos;third party&apos; refers to the website or domain placing the cookie. First-party cookies are set by Hair Restoration of Lehigh Valley directly when you visit our site. Third-party cookies are placed by other companies whose features or services appear on our site. Hair Restoration of Lehigh Valley does not have access to or control over these third-party cookies.</p>
        </Section>

        <Section title="How We Use Cookies">
          <p>We use cookies for a variety of reasons detailed below. Unfortunately, in most cases there are no industry standard options for disabling cookies without completely disabling the functionality and features they add to this site. It is recommended that you leave all cookies enabled if you are not sure whether you need them or not, in case they are used to provide a service that you use.</p>
        </Section>

        <Section title="Analytics Cookies">
          <p>When you visit our website, we may automatically collect certain information about how you browse and interact with the site. We use analytics cookies to better understand how visitors use this site. We use this information to improve the website&apos;s content, structure, and user experience.</p>
          <p><strong>Google Analytics</strong> - This website uses Google Analytics, a web analytics service provided by Google, Inc. Google Analytics uses &quot;cookies&quot; to help the website analyze how users use the site. The information generated by the cookie about your use of the website (including your IP address) will be transmitted to and stored by Google on servers in the United States. Google will use this information for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing other services relating to website activity and internet usage. Google may also transfer this information to third parties where required to do so by law, or where such third parties process the information on Google&apos;s behalf. Google will not associate your IP address with any other data held by Google. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p>
        </Section>

        <Section title="Advertising Cookies">
          <p><strong>Google</strong> - Hair Restoration of Lehigh Valley works with Google to display targeted advertising across the web. These ads may appear on websites unrelated to us and are based on your interests and online behavior. These cookies allow Google to track your browsing patterns across websites. This information is used to help display ads that are more relevant to you.</p>
        </Section>

        <Section title="Flash Cookies">
          <p>We may, in certain situations, use Adobe Flash Player to deliver special content, such as video clips or animation. To improve your user experience, Local Shared Objects (commonly known as &quot;Flash cookies&quot;) are employed to provide functions such as remembering your settings and preferences. Flash cookies are stored on your device, but they are managed through an interface different from the one provided by your web browser. This means it is not possible to manage Flash cookies through your browser in the same way you would manage cookies. Instead, you can access your Flash management tools from Adobe&apos;s website directly. Flash cookies will be deleted when you leave the site.</p>
        </Section>

        <Section title="Web Beacons">
          <p>We may use web beacons (also known as &quot;tracking pixels&quot;) on our website. These are small electronic files that permit us to count users who have visited certain pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</p>
        </Section>

        <Section title="Targeted Advertising">
          <p>Third parties may use cookies, web beacons, and similar technologies to collect or receive information from this website and elsewhere on the internet and use that information to provide measurement services and target ads. You can opt-out of the collection and use of information for ad targeting by visiting <a href="http://www.aboutads.info/choices" target="_blank" rel="noreferrer" style={{ color: DARK }}>www.aboutads.info/choices</a>.</p>
        </Section>

        <Section title="How to Control Cookies">
          <p>You can prevent the setting of cookies by adjusting the settings on your browser (see your browser Help for how to do this). Be aware that disabling cookies will affect the functionality of this and many other websites that you visit. Disabling cookies will usually result in also disabling certain functionality and features of this site. Therefore, it is recommended that you do not disable cookies.</p>
          <p>You can also opt-out of Google Analytics by installing the <a href="https://tools.google.com/dlpage/gaoptout" target="_blank" rel="noreferrer" style={{ color: DARK }}>Google Analytics Opt-out Browser Add-on</a>.</p>
        </Section>

        <Section title="How Often Will We Update This Cookie Policy">
          <p>We may update this Cookie Policy from time to time to reflect, for example, changes to the cookies we use or for other operational, legal, or regulatory reasons. Please therefore re-visit this Cookie Policy regularly to stay informed about our use of cookies and related technologies.</p>
          <p>The date at the top of this Cookie Policy indicates when it was last updated.</p>
        </Section>

        <Section title="Contact Us">
          <p>If you have any questions about our use of cookies or other technologies, please email us at <a href="mailto:info@pahairtransplant.com" style={{ color: DARK }}>info@pahairtransplant.com</a> or contact us at:</p>
          <address style={{ fontStyle: 'normal', color: '#444', lineHeight: 1.9, marginTop: 8 }}>
            <strong>Hair Restoration of Lehigh Valley</strong><br />
            42A S. 3rd St. Suite 201<br />
            Easton, PA 18042<br />
            <a href="tel:4842762638" style={{ color: DARK }}>484-276-2638</a>
          </address>
        </Section>
      </main>

      {/* Footer */}
      <footer style={{ background: WHITE, borderTop: '1px solid #e8e8e8', padding: '32px 48px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10 }}>
        <img src="/logo-pa.webp" alt="Hair Restoration of Lehigh Valley" style={{ height: 44, width: 'auto' }} />
        <p style={{ color: '#555', fontSize: 13, margin: 0 }}>
          42A S. 3rd St. Suite 201, Easton, PA 18042
        </p>
        <p style={{ fontSize: 13, margin: 0 }}>
          <a href="/privacy-policy" style={{ color: '#555', textDecoration: 'none', marginRight: 16 }}>Privacy Policy</a>
          <a href="/cookie-policy" style={{ color: '#555', textDecoration: 'none' }}>Cookie Policy</a>
        </p>
      </footer>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: 48 }}>
      <h2 style={{ fontSize: 18, fontWeight: 700, color: '#2a2a34', marginBottom: 16, paddingBottom: 10, borderBottom: '2px solid #e8e8e8' }}>
        {title}
      </h2>
      <div style={{ fontSize: 15, lineHeight: 1.85, color: '#444', display: 'flex', flexDirection: 'column', gap: 14 }}>
        {children}
      </div>
    </section>
  )
}
